"""set null on question delete

Revision ID: 1197d1a54de0
Revises: e3a8a3be68a8
Create Date: 2026-08-18 02:29:16.020670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1197d1a54de0'
down_revision: Union[str, Sequence[str], None] = 'e3a8a3be68a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('conversation_turns_question_id_fkey'), 'conversation_turns', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_turns', 'questions', ['question_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversation_turns', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_turns_question_id_fkey'), 'conversation_turns', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###
