"""add question metadata fields

Revision ID: e3a8a3be68a8
Revises: afb83ab05185
Create Date: 2026-08-18 02:12:49.742876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3a8a3be68a8'
down_revision: Union[str, Sequence[str], None] = 'afb83ab05185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('questions', sa.Column('question_type', sa.String(length=50), nullable=False, server_default='text'))
    op.add_column('questions', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('questions', sa.Column('options', sa.JSON(), nullable=True))
    op.add_column('questions', sa.Column('required', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('questions', sa.Column('allow_other', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('questions', sa.Column('weight', sa.Float(), nullable=False, server_default='1.0'))
    op.add_column('questions', sa.Column('analysis_dimension', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'analysis_dimension')
    op.drop_column('questions', 'weight')
    op.drop_column('questions', 'allow_other')
    op.drop_column('questions', 'required')
    op.drop_column('questions', 'options')
    op.drop_column('questions', 'category')
    op.drop_column('questions', 'question_type')
    # ### end Alembic commands ###
